vim.opt.termguicolors = true
require('bufferline').setup{
        options = {
            mode = "buffers", -- set to "tabs" to only show tabpages instead
            -- numbers = "none" | "ordinal" | "buffer_id" | "both" | function({ ordinal, id, lower, raise }): string,
            -- close_command = "bdelete! %d",       -- can be a string | function, see "Mouse actions"
            -- right_mouse_command = "bdelete! %d", -- can be a string | function, see "Mouse actions"
            -- left_mouse_command = "buffer %d",    -- can be a string | function, see "Mouse actions"
            -- middle_mouse_command = nil,          -- can be a string | function, see "Mouse actions"
            indicator = {
                -- icon = '▎', -- this should be omitted if indicator style is not 'icon'
                -- style = 'icon' | 'underline' | 'none',
                style = 'none',
            },
            buffer_close_icon = '✕',
            -- modified_icon = '●',
            -- close_icon = '',
            -- left_trunc_marker = '',
            left_trunc_marker = '',
            -- right_trunc_marker = '',
            -- --- name_formatter can be used to change the buffer's label in the bufferline.
            -- --- Please note some names can/will break the
            -- --- bufferline so use this at your discretion knowing that it has
            -- --- some limitations that will *NOT* be fixed.
            -- name_formatter = function(buf)  -- buf contains a "name", "path" and "bufnr"
            --     -- remove extension from markdown files for example
            --     if buf.name:match('%.md') then
            --         return vim.fn.fnamemodify(buf.name, ':t:r')
            --     end
            -- end,
            -- max_name_length = 18,
            -- max_prefix_length = 15, -- prefix used when a buffer is de-duplicated
            -- tab_size = 18,
            diagnostics = false, -- false | "nvim_lsp" | "coc",
            -- diagnostics_update_in_insert = false,
            -- -- The diagnostics indicator can be set to nil to keep the buffer name highlight but delete the highlighting
            -- diagnostics_indicator = function(count, level, diagnostics_dict, context)
            --     return "("..count..")"
            -- end,
            -- -- NOTE: this will be called a lot so don't do any heavy processing here
            -- custom_filter = function(buf_number, buf_numbers)
            --     -- filter out filetypes you don't want to see
            --     if vim.bo[buf_number].filetype ~= "<i-dont-want-to-see-this>" then
            --         return true
            --     end
            --     -- filter out by buffer name
            --     if vim.fn.bufname(buf_number) ~= "<buffer-name-I-dont-want>" then
            --         return true
            --     end
            --     -- filter out based on arbitrary rules
            --     -- e.g. filter out vim wiki buffer from tabline in your work repo
            --     if vim.fn.getcwd() == "<work-repo>" and vim.bo[buf_number].filetype ~= "wiki" then
            --         return true
            --     end
            --     -- filter out by it's index number in list (don't show first buffer)
            --     if buf_numbers[1] ~= buf_number then
            --         return true
            --     end
            -- end,
            offsets = {
                {
                    filetype = "NvimTree",
                    text = "File Explorer",
                    text_align = "left",
                    separator = true,
                }
            },
            -- color_icons = true | false, -- whether or not to add the filetype icon highlights
            -- show_buffer_icons = true | false, -- disable filetype icons for buffers
            -- show_buffer_close_icons = true | false,
            -- show_buffer_default_icon = true | false, -- whether or not an unrecognised filetype should show a default icon
            -- show_close_icon = true | false,
            -- show_tab_indicators = true | false,
            -- persist_buffer_sort = true, -- whether or not custom sorted buffers should persist
            -- -- can also be a table containing 2 custom separators
            -- -- [focused and unfocused]. eg: { '|', '|' }
            separator_style = "thin", -- "slant" | "thick" | "thin" | { 'any', 'any' },
            -- enforce_regular_tabs = false | true,
            -- always_show_bufferline = true | false,
            -- sort_by = 'insert_after_current' |'insert_at_end' | 'id' | 'extension' | 'relative_directory' | 'directory' | 'tabs' | function(buffer_a, buffer_b)
            --     -- add custom logic
            --     return buffer_a.modified > buffer_b.modified
            -- end
        },
        highlights = {
            -- fill = {
            --     -- fg = '<color-value-here>',
            --     -- bg = '#ffffff',
            -- },
            -- background = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- tab = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- tab_selected = {
            --     fg = tabline_sel_bg,
            --     bg = '<color-value-here>'
            -- },
            -- tab_close = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- close_button = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- close_button_visible = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- close_button_selected = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- buffer_visible = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            buffer_selected = {
                -- fg = normal_fg,
                -- bg = '<color-value-here>',
                bold = false,
                -- italic = true,
            },
            -- numbers = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>',
            -- },
            -- numbers_visible = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>',
            -- },
            -- numbers_selected = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>',
            --     bold = true,
            --     italic = true,
            -- },
            -- diagnostic = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>',
            -- },
            -- diagnostic_visible = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>',
            -- },
            -- diagnostic_selected = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>',
            --     bold = true,
            --     italic = true,
            -- },
            -- hint = {
            --     fg = '<color-value-here>',
            --     sp = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- hint_visible = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- hint_selected = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>',
            --     sp = '<color-value-here>'
            --     bold = true,
            --     italic = true,
            -- },
            -- hint_diagnostic = {
            --     fg = '<color-value-here>',
            --     sp = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- hint_diagnostic_visible = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- hint_diagnostic_selected = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>',
            --     sp = '<color-value-here>'
            --     bold = true,
            --     italic = true,
            -- },
            -- info = {
            --     fg = '<color-value-here>',
            --     sp = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- info_visible = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- info_selected = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>',
            --     sp = '<color-value-here>'
            --     bold = true,
            --     italic = true,
            -- },
            -- info_diagnostic = {
            --     fg = '<color-value-here>',
            --     sp = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- info_diagnostic_visible = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- info_diagnostic_selected = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>',
            --     sp = '<color-value-here>'
            --     bold = true,
            --     italic = true,
            -- },
            -- warning = {
            --     fg = '<color-value-here>',
            --     sp = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- warning_visible = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- warning_selected = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>',
            --     sp = '<color-value-here>'
            --     bold = true,
            --     italic = true,
            -- },
            -- warning_diagnostic = {
            --     fg = '<color-value-here>',
            --     sp = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- warning_diagnostic_visible = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- warning_diagnostic_selected = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>',
            --     sp = warning_diagnostic_fg
            --     bold = true,
            --     italic = true,
            -- },
            -- error = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>',
            --     sp = '<color-value-here>'
            -- },
            -- error_visible = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- error_selected = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>',
            --     sp = '<color-value-here>'
            --     bold = true,
            --     italic = true,
            -- },
            -- error_diagnostic = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>',
            --     sp = '<color-value-here>'
            -- },
            -- error_diagnostic_visible = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- error_diagnostic_selected = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>',
            --     sp = '<color-value-here>'
            --     bold = true,
            --     italic = true,
            -- },
            -- modified = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- modified_visible = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- modified_selected = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- duplicate_selected = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            --     italic = true,
            -- },
            -- duplicate_visible = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            --     italic = true
            -- },
            -- duplicate = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            --     italic = true
            -- },
            -- separator_selected = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- separator_visible = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- separator = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- indicator_selected = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>'
            -- },
            -- pick_selected = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>',
            --     bold = true,
            --     italic = true,
            -- },
            -- pick_visible = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>',
            --     bold = true,
            --     italic = true,
            -- },
            -- pick = {
            --     fg = '<color-value-here>',
            --     bg = '<color-value-here>',
            --     bold = true,
            --     italic = true,
            -- },
            offset_separator = {
                -- fg = '<color-value-here>',
                -- bg = 'transarent',
            },
        };
}
